# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.0.3
group=dev.iuif.sublang
java_version=17

# Common
minecraft_version=1.18.2
mod_name=SubLang
mod_author=iuif
mod_id=sublang
license=MIT
credits=
description=Display item names in bilingual format (TranslatedName (OriginalName)) for easier JEI searching.
minecraft_version_range=[1.18.2, 1.19)

# Parchment mappings
parchment_minecraft=1.18.2
parchment_version=2022.11.06

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.76.0+1.18.2
fabric_loader_version=0.14.22

# Forge (not used in this version - Fabric only)
forge_version=40.2.21
forge_loader_version_range=[40,)

# NeoForge (not used in this version - Fabric only)
neoforge_version=0.0.0
neoforge_loader_version_range=[0,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
