# Project
version=1.0.0
group=dev.iuif.sublang

# Common
minecraft_version=1.12.2
mod_name=SubLang
mod_author=iuif
mod_id=sublang
license=MIT
description=Display item names in bilingual format (TranslatedName (OriginalName)) for easier JEI searching.

# Forge
forge_version=14.23.5.2860

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
